// <auto-generated />
using System;
using ForcePlatformData.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForcePlatformData.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20231127074304_BasMigration002")]
    partial class BasMigration002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("ForcePlatformData.DbModels.ExerciseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ExerciseTypeId");

                    b.ToTable("ExerciseTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Stability, 1st platform"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jump, 2 platforms"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gait, 4 platforms"
                        });
                });

            modelBuilder.Entity("ForcePlatformData.DbModels.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilterLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_ReportId");

                    b.HasIndex("ExerciseTypeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("ForcePlatformData.DbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_UserId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ForcePlatformData.DbModels.UserParams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BodyHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("BodyWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LeftForearm")
                        .HasColumnType("REAL");

                    b.Property<double?>("LeftHand")
                        .HasColumnType("REAL");

                    b.Property<double?>("LeftShin")
                        .HasColumnType("REAL");

                    b.Property<double?>("LeftSole")
                        .HasColumnType("REAL");

                    b.Property<double?>("LeftTigh")
                        .HasColumnType("REAL");

                    b.Property<double?>("LeftUpperLimb")
                        .HasColumnType("REAL");

                    b.Property<string>("LengthUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("RightForearm")
                        .HasColumnType("REAL");

                    b.Property<double?>("RightHand")
                        .HasColumnType("REAL");

                    b.Property<double?>("RightShin")
                        .HasColumnType("REAL");

                    b.Property<double?>("RightSole")
                        .HasColumnType("REAL");

                    b.Property<double?>("RightTigh")
                        .HasColumnType("REAL");

                    b.Property<double?>("RightUpperLimb")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_UserParamId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserParams", (string)null);
                });

            modelBuilder.Entity("ForcePlatformData.DbModels.Report", b =>
                {
                    b.HasOne("ForcePlatformData.DbModels.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForcePlatformData.DbModels.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForcePlatformData.DbModels.UserParams", b =>
                {
                    b.HasOne("ForcePlatformData.DbModels.User", "User")
                        .WithOne("UserParams")
                        .HasForeignKey("ForcePlatformData.DbModels.UserParams", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForcePlatformData.DbModels.User", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("UserParams")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
